USE [master]
GO
/****** Object:  Database [AttendentsDB]    Script Date: 1/3/2023 1:35:45 PM ******/
CREATE DATABASE [AttendentsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AttendentsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER02\MSSQL\DATA\AttendentsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AttendentsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER02\MSSQL\DATA\AttendentsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AttendentsDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AttendentsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AttendentsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AttendentsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AttendentsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AttendentsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AttendentsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AttendentsDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AttendentsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AttendentsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AttendentsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AttendentsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AttendentsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AttendentsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AttendentsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AttendentsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AttendentsDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AttendentsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AttendentsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AttendentsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AttendentsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AttendentsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AttendentsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AttendentsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AttendentsDB] SET RECOVERY FULL 
GO
ALTER DATABASE [AttendentsDB] SET  MULTI_USER 
GO
ALTER DATABASE [AttendentsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AttendentsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AttendentsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AttendentsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AttendentsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AttendentsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AttendentsDB', N'ON'
GO
ALTER DATABASE [AttendentsDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [AttendentsDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AttendentsDB]
GO
/****** Object:  Table [dbo].[attendance]    Script Date: 1/3/2023 1:35:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[attendance](
	[studentid] [int] NULL,
	[regno] [varchar](40) NULL,
	[week] [varchar](40) NULL,
	[date] [date] NULL,
	[attended] [varchar](40) NULL,
	[id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[courses]    Script Date: 1/3/2023 1:35:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[courses](
	[id] [int] NOT NULL,
	[name] [varchar](40) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[membership_groups]    Script Date: 1/3/2023 1:35:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[membership_groups](
	[groupID] [int] NOT NULL,
	[name] [varchar](20) NULL,
	[description] [text] NULL,
	[allowSignup] [int] NULL,
	[needsApproval] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[students]    Script Date: 1/3/2023 1:35:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[students](
	[studentid] [int] NOT NULL,
	[regno] [varchar](40) NOT NULL,
	[name] [varchar](100) NOT NULL,
	[course] [varchar](40) NULL,
PRIMARY KEY CLUSTERED 
(
	[studentid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[attendance] ADD  DEFAULT (NULL) FOR [studentid]
GO
ALTER TABLE [dbo].[attendance] ADD  DEFAULT (NULL) FOR [regno]
GO
ALTER TABLE [dbo].[attendance] ADD  DEFAULT (NULL) FOR [week]
GO
ALTER TABLE [dbo].[attendance] ADD  DEFAULT (NULL) FOR [date]
GO
ALTER TABLE [dbo].[attendance] ADD  DEFAULT (NULL) FOR [attended]
GO
ALTER TABLE [dbo].[courses] ADD  DEFAULT (NULL) FOR [name]
GO
ALTER TABLE [dbo].[membership_groups] ADD  DEFAULT (NULL) FOR [name]
GO
ALTER TABLE [dbo].[membership_groups] ADD  DEFAULT (NULL) FOR [description]
GO
ALTER TABLE [dbo].[membership_groups] ADD  DEFAULT (NULL) FOR [allowSignup]
GO
ALTER TABLE [dbo].[membership_groups] ADD  DEFAULT (NULL) FOR [needsApproval]
GO
ALTER TABLE [dbo].[students] ADD  DEFAULT (NULL) FOR [course]
GO
ALTER TABLE [dbo].[attendance]  WITH CHECK ADD FOREIGN KEY([studentid])
REFERENCES [dbo].[students] ([studentid])
GO
USE [master]
GO
ALTER DATABASE [AttendentsDB] SET  READ_WRITE 
GO
